config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'

  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  has_one_attached :photo

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: [:list_id] }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  # A bookmark must be linked to a movie and a list,
  # and the [movie, list] pairings should be unique.
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list), notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), notice: 'Bookmark was successfully destroyed.'
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :photo)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'Your watchlist was successfully created.'
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Create new bookmark</h1>
<%= simple_form_for ([ @list, @bookmark ]) do |f| %>
<div class="form-inputs">
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Create new bookmark", class: "btn btn-flat" %>
</div>
<% end %>
<br>
<%= link_to 'Back to watchlist', list_path(@list), class: 'btn btn-flat' %>

app/views/layouts/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.7)), url(https://images.unsplash.com/photo-1536440136628-849c177e76a1);">
  <div class="container-ban">
    <h1>Remember <strong>movies</strong> you got <strong>recommended</strong></h1>
    <p>Save your favorite movies to your watchlist!</p>
    <center><a class="btn btn-flat" href="/lists/new">Create a watchlist</a></center>
  </div>
</div>

app/views/layouts/_cards.html.erb
<div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2>Title here</h2>
      <p>Short description here!</p>
    </div>
    <h2 class="card-trip-pricing">£99.99</h2>
    <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This app was made with <i class="fas fa-heart"></i> at Le Wagon Cologne
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to lists_path, class: "navbar-brand" do %>
      <%= image_tag "https://i.ibb.co/0JBgJDD/logo.png" %>
      <span class="logo-text"></span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse navlink" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My lists", lists_path(@list), class: "btn btn-ghost" %>
          </li>
          <li class="nav-item">
            <%= link_to "New list", new_list_path(@list), class: "btn btn-ghost" %>
          </li>

        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovCrate - Create your watchlist.</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/banner" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>My watchlists</h1>
<div class="watchlists">
  <% @lists.each do |list| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1568876694728-451bbf694b83)">
      <%=  link_to list.name, list_path(list) %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>Create new watchlist</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions btn btn-flat">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/show.html.erb
<h1 class"text-center"><%= @list.name %></h1>
<div class="cards">
  <% @bookmarks.each do |bm| %>
    <div class="card-trip">
      <img src="https://images.unsplash.com/photo-1542204165-65bf26472b9b" />
      <div class="card-trip-infos">
        <div>
          <h2><%= bm.movie.title %></h2>
          <p><%= bm.movie.overview %></p>
        </div>
        <h2 class="card-trip-pricing"><%= bm.movie.rating %></h2>
      </div>
    </div>
  <% end %>
</div>
<%= link_to 'All watchlists', lists_path(@list), class: 'btn btn-flat' %>
<%= link_to 'Create new bookmark', new_list_bookmark_path(@list), class: 'btn btn-flat' %>